[workspace]
resolver = "3"
members = ["crates/fusen-core", "apps/cli", "apps/desktop/src-tauri"]

[workspace.package]
version = "0.1.4"
edition = "2024"
rust-version = "1.88"
license = "MIT"

[workspace.dependencies]
fusen-core = { path = "crates/fusen-core" }

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
