[package]
name = "fusen-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
name = "fusen_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
arboard = { version = "3.6.1", default-features = false }
fusen-core.workspace = true
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-single-instance = "2.4.5"
notify-debouncer-mini = "0.7.0"
ts-rs = "12.0.1"
percent-encoding = "2.3.2"
tauri-plugin-opener = "2.5.5"
