// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FusenState } from "./FusenState";

/**
 * A document and its fusen, as shown in the Fusen window.
 */
export type DocumentState = { path: string, content: string, hash: string, fusen: Array<FusenState>, };
