// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Anchor } from "./Anchor";
import type { Reply } from "./Reply";
import type { State } from "./State";
import type { Status } from "./Status";

export type FusenState = { state: State, id: string, kind: string, status: Status, body: string, anchor: Anchor | null, docHash: string, createdAt: string, replies: Array<Reply>, };
