// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A fusen kind, with defaults filled in.
 */
export type Kind = { id: string, label: string, description: string | null, color: string, };
