// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The range of the document a new fusen refers to.
 */
export type NewAnchor = { quote: string, lines: string, };
