// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What `fusen <path>` asked the window to show.
 */
export type SessionInfo = { 
/**
 * Absolute path of the project root.
 */
root: string, 
/**
 * `true` for `fusen <file>`: only that file is listed.
 */
singleFile: boolean, 
/**
 * The directory or file whose Markdown files are listed, relative to the root.
 */
scope: string, 
/**
 * The document to open first, if any.
 */
document: string | null, };
