// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Kind } from "./Kind";

/**
 * All settings, with defaults filled in.
 */
export type Settings = { userName: string, language: string, 
/**
 * `light` or `dark`.
 */
theme: string, kinds: Array<Kind>, };
