// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a fusen is shown and filtered. Each fusen is in exactly one state.
 */
export type State = "open" | "outdated" | "closed";
